[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && node src/server.js"

[variables]
PORT = "8080"
