[phases.setup]
nixPkgs = ["nodejs-18_x", "openssl"]

[phases.install]
cmds = ["npm ci --omit=dev --ignore-scripts"]

[phases.build]
cmds = []

[start]
cmd = "npx prisma generate && echo 'Prisma Client Generated' && npx prisma migrate deploy && echo 'Migration Completed' && npm start"
